version: '3.8'

services:
  api_one:
    build: ./services/api_one
    ports:
      - "8001:8001"
  api_two:
    build: ./services/api_two
    ports:
      - "8002:8002"
  consumer:
    build: ./services/consumer
    ports:
      - "8000:8000"
    depends_on:
      - api_one
      - api_two
